### ISSUE TITLE
Warning bigdecimal will no longer be part of Ruby 3.4.0

### ISSUE THREAD

**Issue by fukayatsu** [r18n/r18n-core#107]
```
$ ruby -v
ruby 3.3.4 (2024-07-09 revision be1089c8ec) +YJIT [x86_64-linux]
```

```
/app/vendor/bundle/ruby/3.3.0/gems/r18n-core-5.0.1/lib/r18n-core/locale.rb:21: warning: bigdecimal was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add bigdecimal to your Gemfile or gemspec. Also contact author of r18n-core-5.0.1 to add bigdecimal into its gemspec.
```

**Comment by simonneutert** [comment]
I would volunteer if needed, just let me know 🙋‍♂️

**Comment by AlexWayfer** [comment]
How can I reproduce it? With `bundle exec rspec` and Ruby 3.3.5 I see no warnings about `bigdecimal`.

**Comment by simonneutert** [comment]
## Provoke the warning in a mini example

Hope this helps 🤞 

You need `rackup` to run the tiny `roda` based example.

```shell
gem install rackup
```

Then create a new directory and put the following file named `config.ru` in it. It is the example from [roda's landing page](https://roda.jeremyevans.net), with the bundler bits you need to actually run.

```ruby
# content of config.ru
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem "roda-i18n", "~> 0.6.0"
  gem "roda", "~> 3.84"
end

# cat config.ru
require "roda"

class App < Roda
  plugin :i18n

  route do |r|
    # GET / request
    r.root do
      r.redirect "/hello"
    end

    # /hello branch
    r.on "hello" do
      # Set variable for all routes in /hello branch
      @greeting = 'Hello'

      # GET /hello/world request
      r.get "world" do
        "#{@greeting} world!"
      end

      # /hello request
      r.is do
        # GET /hello request
        r.get do
          "#{@greeting}!"
        end

        # POST /hello request
        r.post do
          puts "Someone said #{@greeting}!"
          r.redirect
        end
      end
    end
  end
end

run App.freeze.app
```

run this app / `config.ru` file:

```shell
$ rackup
```

## Screenshot

<details>

<summary>Screenshot 📸</summary>

<img width="1072" alt="image" src="https://github.com/user-attachments/assets/fac83549-079c-4c90-a153-7fca42b820f2">

</details>

**Comment by AlexWayfer** [comment]
It's weird that `bundle exec rspec` doesn't display this warning, but I can confirm with your example. 

I've just added `gem "puma"`, because `roda` requires any web-server. And `gem "r18n-core", path: '.'` for local testing.

Thank you for this.
